// Auto-generated from forge build artifacts. Re-run after contract changes.

export const IDEA_REGISTRY_ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "VOTING_WINDOW", inputs: [], outputs: [{ name: "", type: "uint64" }], stateMutability: "view" },
  { type: "function", name: "accumulateVote", inputs: [{ name: "ideaId", type: "uint256" }, { name: "isYes", type: "bool" }, { name: "weight", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getIdea", inputs: [{ name: "ideaId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "id", type: "uint256" }, { name: "titleHash", type: "bytes32" }, { name: "founder", type: "address" }, { name: "publishedAt", type: "uint64" }, { name: "closesAt", type: "uint64" }, { name: "status", type: "uint8" }, { name: "yesWeight", type: "uint256" }, { name: "noWeight", type: "uint256" }, { name: "pmfScore", type: "uint32" }] }], stateMutability: "view" },
  { type: "function", name: "ideaCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "ideas", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "id", type: "uint256" }, { name: "titleHash", type: "bytes32" }, { name: "founder", type: "address" }, { name: "publishedAt", type: "uint64" }, { name: "closesAt", type: "uint64" }, { name: "status", type: "uint8" }, { name: "yesWeight", type: "uint256" }, { name: "noWeight", type: "uint256" }, { name: "pmfScore", type: "uint32" }], stateMutability: "view" },
  { type: "function", name: "isVotingOpen", inputs: [{ name: "ideaId", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "registerIdea", inputs: [{ name: "titleHash", type: "bytes32" }], outputs: [{ name: "ideaId", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "resolveIdea", inputs: [{ name: "ideaId", type: "uint256" }, { name: "won", type: "bool" }, { name: "pmfScore", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setVotingEngine", inputs: [{ name: "_votingEngine", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "votingEngine", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event", name: "IdeaRegistered", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "founder", type: "address", indexed: true }, { name: "titleHash", type: "bytes32", indexed: false }, { name: "closesAt", type: "uint64", indexed: false }], anonymous: false },
  { type: "event", name: "IdeaResolved", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "won", type: "bool", indexed: false }, { name: "pmfScore", type: "uint32", indexed: false }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "VotingEngineSet", inputs: [{ name: "votingEngine", type: "address", indexed: true }], anonymous: false },
  { type: "error", name: "IdeaDoesNotExist", inputs: [] },
  { type: "error", name: "IdeaNotActive", inputs: [] },
  { type: "error", name: "NotVotingEngine", inputs: [] },
  { type: "error", name: "VotingClosed", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
] as const

export const VOTING_ENGINE_ABI = [
  { type: "constructor", inputs: [{ name: "_registry", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "MULTIPLIER_EARLY", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MULTIPLIER_LATE", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MULTIPLIER_MID", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "SCALE", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "castVote", inputs: [{ name: "ideaId", type: "uint256" }, { name: "direction", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "computeWeightAndTier", inputs: [{ name: "elapsedSeconds", type: "uint64" }], outputs: [{ name: "weight", type: "uint256" }, { name: "tier", type: "uint8" }], stateMutability: "pure" },
  { type: "function", name: "getVoteRecord", inputs: [{ name: "ideaId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "", type: "tuple", components: [{ name: "hasVoted", type: "bool" }, { name: "direction", type: "bool" }, { name: "weight", type: "uint256" }, { name: "tier", type: "uint8" }, { name: "castedAt", type: "uint64" }] }], stateMutability: "view" },
  { type: "function", name: "registry", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "voteRecords", inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], outputs: [{ name: "hasVoted", type: "bool" }, { name: "direction", type: "bool" }, { name: "weight", type: "uint256" }, { name: "tier", type: "uint8" }, { name: "castedAt", type: "uint64" }], stateMutability: "view" },
  { type: "event", name: "VoteCast", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "voter", type: "address", indexed: true }, { name: "direction", type: "bool", indexed: false }, { name: "weight", type: "uint256", indexed: false }, { name: "tier", type: "uint8", indexed: false }], anonymous: false },
  { type: "error", name: "AlreadyVoted", inputs: [] },
  { type: "error", name: "IdeaNotActive", inputs: [] },
  { type: "error", name: "VotingClosed", inputs: [] },
] as const

export const CONVICTION_TOKEN_ABI = [
  { type: "constructor", inputs: [{ name: "name_", type: "string" }, { name: "symbol_", type: "string" }, { name: "minter_", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "MAX_SUPPLY", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ name: "", type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "mint", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "minter", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "name", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "transferFrom", inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "event", name: "Approval", inputs: [{ name: "owner", type: "address", indexed: true }, { name: "spender", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }], anonymous: false },
  { type: "error", name: "CapExceeded", inputs: [] },
  { type: "error", name: "ERC20InsufficientAllowance", inputs: [{ name: "spender", type: "address" }, { name: "allowance", type: "uint256" }, { name: "needed", type: "uint256" }] },
  { type: "error", name: "ERC20InsufficientBalance", inputs: [{ name: "sender", type: "address" }, { name: "balance", type: "uint256" }, { name: "needed", type: "uint256" }] },
  { type: "error", name: "ERC20InvalidApprover", inputs: [{ name: "approver", type: "address" }] },
  { type: "error", name: "ERC20InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
  { type: "error", name: "ERC20InvalidSender", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "ERC20InvalidSpender", inputs: [{ name: "spender", type: "address" }] },
  { type: "error", name: "NotMinter", inputs: [] },
] as const

export const CONVICTION_TOKEN_FACTORY_ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "launch", inputs: [{ name: "ideaId", type: "uint256" }, { name: "name", type: "string" }, { name: "symbol", type: "string" }], outputs: [{ name: "token", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "mint", inputs: [{ name: "ideaId", type: "uint256" }, { name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "mintForCurve", inputs: [{ name: "token", type: "address" }, { name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "registerCurve", inputs: [{ name: "token", type: "address" }, { name: "curve", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "tokenForIdea", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "TokenLaunched", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "token", type: "address", indexed: false }], anonymous: false },
  { type: "error", name: "AlreadyLaunched", inputs: [] },
  { type: "error", name: "NotAuthorisedCurve", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
] as const

export const BONDING_CURVE_ABI = [
  { type: "constructor", inputs: [{ name: "ideaId_", type: "uint256" }, { name: "token_", type: "address" }, { name: "buildFund_", type: "address" }, { name: "factory_", type: "address" }], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  { type: "function", name: "BASE_PRICE", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "BUILD_FUND_BPS", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "GRADUATION_TARGET", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MAX_SUPPLY", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "buildFund", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "buy", inputs: [{ name: "minTokensOut", type: "uint256" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "factory", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "getEthForTokens", inputs: [{ name: "tokenAmount", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getTokensForEth", inputs: [{ name: "ethAmount", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "graduated", inputs: [], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "ideaId", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "token", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "totalRaised", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "event", name: "Bought", inputs: [{ name: "buyer", type: "address", indexed: true }, { name: "ethIn", type: "uint256", indexed: false }, { name: "tokensOut", type: "uint256", indexed: false }, { name: "newTotalRaised", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "Graduated", inputs: [{ name: "totalRaised", type: "uint256", indexed: false }, { name: "buildFundShare", type: "uint256", indexed: false }], anonymous: false },
  { type: "error", name: "AlreadyGraduated", inputs: [] },
  { type: "error", name: "SlippageExceeded", inputs: [] },
  { type: "error", name: "ZeroValue", inputs: [] },
] as const

export const BONDING_CURVE_FACTORY_ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "curveForIdea", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "launch", inputs: [{ name: "ideaId", type: "uint256" }, { name: "token", type: "address" }, { name: "buildFund", type: "address" }, { name: "tokenFactory", type: "address" }], outputs: [{ name: "curve", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "launchAll", inputs: [{ name: "ideaId", type: "uint256" }, { name: "name", type: "string" }, { name: "symbol", type: "string" }, { name: "buildFund", type: "address" }, { name: "tokenFactory", type: "address" }], outputs: [{ name: "token", type: "address" }, { name: "curve", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "CurveLaunched", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "curve", type: "address", indexed: false }, { name: "token", type: "address", indexed: false }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "error", name: "AlreadyLaunched", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
] as const

export const BUILD_FUND_ABI = [
  { type: "constructor", inputs: [{ name: "beneficiary_", type: "address" }], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  { type: "function", name: "BURN_DEADLINE_OFFSET", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "addMilestone", inputs: [{ name: "description", type: "string" }, { name: "releaseAmount", type: "uint256" }], outputs: [{ name: "milestoneId", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "beneficiary", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "burnDeadline", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "burnUnclaimed", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "deadlineSet", inputs: [], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "milestoneCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "milestones", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "description", type: "string" }, { name: "releaseAmount", type: "uint256" }, { name: "released", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "releaseMilestone", inputs: [{ name: "milestoneId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "totalReceived", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalReleased", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "FundsReceived", inputs: [{ name: "amount", type: "uint256", indexed: false }, { name: "newTotal", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "MilestoneAdded", inputs: [{ name: "milestoneId", type: "uint256", indexed: true }, { name: "description", type: "string", indexed: false }, { name: "releaseAmount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "MilestoneReleased", inputs: [{ name: "milestoneId", type: "uint256", indexed: true }, { name: "amount", type: "uint256", indexed: false }, { name: "beneficiary", type: "address", indexed: false }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "UnclaimedBurned", inputs: [{ name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "error", name: "BurnDeadlineAlreadySet", inputs: [] },
  { type: "error", name: "BurnDeadlineNotReached", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "MilestoneAlreadyReleased", inputs: [] },
  { type: "error", name: "MilestoneDoesNotExist", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "TransferFailed", inputs: [] },
] as const

export const AIRDROP_DISTRIBUTOR_ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claim", inputs: [{ name: "ideaId", type: "uint256" }, { name: "token", type: "address" }, { name: "amount", type: "uint256" }, { name: "proof", type: "bytes32[]" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimed", inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "hasClaimed", inputs: [{ name: "ideaId", type: "uint256" }, { name: "claimer", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "merkleRoots", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setMerkleRoot", inputs: [{ name: "ideaId", type: "uint256" }, { name: "root", type: "bytes32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "Claimed", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "claimer", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "RootSet", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "root", type: "bytes32", indexed: false }], anonymous: false },
  { type: "error", name: "AlreadyClaimed", inputs: [] },
  { type: "error", name: "InvalidProof", inputs: [] },
  { type: "error", name: "NoRootSet", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
] as const

export const REPUTATION_REGISTRY_ABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "approve", inputs: [{ name: "to", type: "address" }, { name: "tokenId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "balanceOf", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getApproved", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "getReputation", inputs: [{ name: "wallet", type: "address" }], outputs: [{ name: "", type: "tuple", components: [{ name: "score", type: "uint8" }, { name: "totalVotes", type: "uint32" }, { name: "correctCalls", type: "uint32" }, { name: "streakDays", type: "uint32" }, { name: "lastUpdated", type: "uint64" }] }], stateMutability: "view" },
  { type: "function", name: "isApprovedForAll", inputs: [{ name: "owner", type: "address" }, { name: "operator", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "mint", inputs: [{ name: "wallet", type: "address" }, { name: "score", type: "uint8" }, { name: "totalVotes", type: "uint32" }, { name: "correctCalls", type: "uint32" }, { name: "streakDays", type: "uint32" }], outputs: [{ name: "tokenId", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "name", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "ownerOf", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "reputation", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "score", type: "uint8" }, { name: "totalVotes", type: "uint32" }, { name: "correctCalls", type: "uint32" }, { name: "streakDays", type: "uint32" }, { name: "lastUpdated", type: "uint64" }], stateMutability: "view" },
  { type: "function", name: "safeTransferFrom", inputs: [{ name: "", type: "address" }, { name: "", type: "address" }, { name: "", type: "uint256" }, { name: "", type: "bytes" }], outputs: [], stateMutability: "pure" },
  { type: "function", name: "setApprovalForAll", inputs: [{ name: "operator", type: "address" }, { name: "approved", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "supportsInterface", inputs: [{ name: "interfaceId", type: "bytes4" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "tokenOfWallet", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "tokenURI", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "transferFrom", inputs: [{ name: "", type: "address" }, { name: "", type: "address" }, { name: "", type: "uint256" }], outputs: [], stateMutability: "pure" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updateReputation", inputs: [{ name: "wallet", type: "address" }, { name: "score", type: "uint8" }, { name: "totalVotes", type: "uint32" }, { name: "correctCalls", type: "uint32" }, { name: "streakDays", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "Approval", inputs: [{ name: "owner", type: "address", indexed: true }, { name: "approved", type: "address", indexed: true }, { name: "tokenId", type: "uint256", indexed: true }], anonymous: false },
  { type: "event", name: "ApprovalForAll", inputs: [{ name: "owner", type: "address", indexed: true }, { name: "operator", type: "address", indexed: true }, { name: "approved", type: "bool", indexed: false }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "ReputationMinted", inputs: [{ name: "wallet", type: "address", indexed: true }, { name: "tokenId", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "ReputationUpdated", inputs: [{ name: "wallet", type: "address", indexed: true }, { name: "tokenId", type: "uint256", indexed: false }, { name: "score", type: "uint8", indexed: false }], anonymous: false },
  { type: "event", name: "Transfer", inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "tokenId", type: "uint256", indexed: true }], anonymous: false },
  { type: "error", name: "AlreadyMinted", inputs: [] },
  { type: "error", name: "ERC721IncorrectOwner", inputs: [{ name: "sender", type: "address" }, { name: "tokenId", type: "uint256" }, { name: "owner", type: "address" }] },
  { type: "error", name: "ERC721InsufficientApproval", inputs: [{ name: "operator", type: "address" }, { name: "tokenId", type: "uint256" }] },
  { type: "error", name: "ERC721InvalidApprover", inputs: [{ name: "approver", type: "address" }] },
  { type: "error", name: "ERC721InvalidOperator", inputs: [{ name: "operator", type: "address" }] },
  { type: "error", name: "ERC721InvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "ERC721InvalidReceiver", inputs: [{ name: "receiver", type: "address" }] },
  { type: "error", name: "ERC721InvalidSender", inputs: [{ name: "sender", type: "address" }] },
  { type: "error", name: "ERC721NonexistentToken", inputs: [{ name: "tokenId", type: "uint256" }] },
  { type: "error", name: "NotYetMinted", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "Soulbound", inputs: [] },
] as const

export const SOVEREIGN_AGENT_ABI = [
  { type: "constructor", inputs: [{ name: "name_", type: "string" }, { name: "version_", type: "string" }, { name: "operator_", type: "address" }, { name: "feeRecipient_", type: "address" }], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  { type: "function", name: "FEE_BPS", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "agentName", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "agentVersion", inputs: [], outputs: [{ name: "", type: "string" }], stateMutability: "view" },
  { type: "function", name: "attestations", inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "ideaId", type: "uint256" }, { name: "qualityScore", type: "uint8" }, { name: "reasoning", type: "string" }, { name: "eigenDaRef", type: "bytes32" }, { name: "timestamp", type: "uint64" }, { name: "exists", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "feeRecipient", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "getAttestation", inputs: [{ name: "ideaId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "ideaId", type: "uint256" }, { name: "qualityScore", type: "uint8" }, { name: "reasoning", type: "string" }, { name: "eigenDaRef", type: "bytes32" }, { name: "timestamp", type: "uint64" }, { name: "exists", type: "bool" }] }], stateMutability: "view" },
  { type: "function", name: "hasAttestation", inputs: [{ name: "ideaId", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "operator", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "postAttestation", inputs: [{ name: "ideaId", type: "uint256" }, { name: "qualityScore", type: "uint8" }, { name: "reasoning", type: "string" }, { name: "eigenDaRef", type: "bytes32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "routeFees", inputs: [{ name: "recipient", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setFeeRecipient", inputs: [{ name: "newFeeRecipient", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setOperator", inputs: [{ name: "newOperator", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "totalFeesRouted", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updateAttestation", inputs: [{ name: "ideaId", type: "uint256" }, { name: "qualityScore", type: "uint8" }, { name: "reasoning", type: "string" }, { name: "eigenDaRef", type: "bytes32" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "AttestationPosted", inputs: [{ name: "ideaId", type: "uint256", indexed: true }, { name: "qualityScore", type: "uint8", indexed: false }, { name: "eigenDaRef", type: "bytes32", indexed: false }, { name: "timestamp", type: "uint64", indexed: false }], anonymous: false },
  { type: "event", name: "FeeReceived", inputs: [{ name: "from", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "FeeRecipientUpdated", inputs: [{ name: "newFeeRecipient", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "FeeRouted", inputs: [{ name: "to", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "OperatorUpdated", inputs: [{ name: "oldOperator", type: "address", indexed: true }, { name: "newOperator", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "OwnershipTransferred", inputs: [{ name: "previousOwner", type: "address", indexed: true }, { name: "newOwner", type: "address", indexed: true }], anonymous: false },
  { type: "error", name: "AlreadyAttested", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  { type: "error", name: "NotOperator", inputs: [] },
  { type: "error", name: "OwnableInvalidOwner", inputs: [{ name: "owner", type: "address" }] },
  { type: "error", name: "OwnableUnauthorizedAccount", inputs: [{ name: "account", type: "address" }] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const
